# Generated by Django 6.1.2 on 2026-10-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stuscore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
                ('grade', models.IntegerField(default=0)),
                ('age', models.IntegerField(default=0)),
                ('stature', models.FloatField(default=0)),
                ('kor', models.IntegerField(default=0)),
                ('eng', models.IntegerField(default=0)),
                ('math', models.IntegerField(default=0)),
                ('sw', models.CharField(max_length=100)),
            ],
        ),
    ]
